apiVersion: v1 
kind: Service
metadata:
  name: learn-devops-api
  labels:
    app: learn-devops-api
spec:
  selector:
    app: learn-devops-api
  ports:
    - protocol: TCP
      ports: 4000 # Serviece Port
      targetPort: 4000 # Container Port
  type: NodePort # change to LoadBalancer if running in cloud