apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-api
  labels:
    app: kubernetes-demo-api
spec:
  selector:
    app: kubernetes-demo-api
  ports:
    - protocol: TCP
      port: 4000 # Service Port
      targetPort: 4000 # Container Port
  type: NodePort # change to LoadBalancer if running in cloud